### ISSUE TITLE
LevelDown built against NAPI Node 6.x fails with NAPI Node-ChakraCore

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#16]
```
C:\git\leveldown>..\NAPI-Node-Chakra\node.exe test\iterator-test.js
TAP version 13
# setUp common
ok 1 cleanup returned an error
# setUp db
TypeError: Object expected
   at LevelDOWN (C:\git\leveldown\leveldown.js:15:3)
   at LevelDOWN (C:\git\leveldown\leveldown.js:12:5)
   at Anonymous function (C:\git\leveldown\node_modules\abstract-leveldown\abstract\iterator-test.js:26:5)
   at bound (C:\git\leveldown\node_modules\tape\lib\test.js:61:21)
   at Test.prototype.run (C:\git\leveldown\node_modules\tape\lib\test.js:80:5)
   at bound (C:\git\leveldown\node_modules\tape\lib\test.js:61:21)
   at next (C:\git\leveldown\node_modules\tape\lib\results.js:70:13)
   at runCallback (timers.js:570:7)
   at tryOnImmediate (timers.js:550:5)
   at processImmediate (timers.js:529:5)
```

**Comment by boingoing** [comment]
This is working after 8512d5f4b16911564bf23a46921ca5a57840f35c and be9dfd870c2a617a193090c91dbf212eb0e5570d
