### ISSUE TITLE
`napi_create_error()` does not create a stack trace when called from `napi_async_complete_callback`

### ISSUE THREAD

**Issue by jorangreef** [nodejs/abi-stable-node#342]
If I call `napi_create_error()` from a synchronous native method call, I receive a stack trace as expected:

```
@ronomon/quorum/basic.js:63
Quorum.quorum(
       ^

Error [ERR_CYCLIC_REFERENCES]: vectors must not have cyclic references
    at Object.<anonymous> (@ronomon/quorum/basic.js:63:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

But if I call `napi_create_error()` from `napi_async_complete_callback`, the stack trace is empty and very surprising:

```
undefined:0



Error [ERR_CYCLIC_REFERENCES]: vectors must not have cyclic references
```

Can this be improved? The `undefined:0` made it seem like N-API had a debug `printf` statement somewhere. It took me awhile to realize this was actually an attempt at a stack trace.

**Comment by mhdawson** [comment]
@jorangreef I've not noticed there has been no reply for a very long time. Sorry about that.

If this is still an issue could you create an issue in the nodejs/node repo along with a reference to the source code we can use to recreate?  We now look at issues there and in node-addon-api regularly in the weekly Node-API team meeting. 

I'm going to close this one. Please let us know if that was not the right thing to do.
